### ISSUE TITLE
os x?

### ISSUE THREAD

**Issue by nilsbecker** [LaurentMazare/ocaml-torch#2] opened 2018-12-17 10:55 UTC
is it a problem in principle to support os x, e.g. due to gpu issues?

`torch unmet availability conditions: os = "linux" `

**Comment by LaurentMazare** [comment] 2018-12-17 11:15
By default the cpu package for libtorch will be installed so gpu should not be an issue there (and one can optionally install the gpu version).
Supporting os x probably just requires adapting the linker flags a generated in [discover.ml](https://github.com/LaurentMazare/ocaml-torch/blob/master/src/config/discover.ml), however I don't have access to a mac so cannot get it to work.
If I can get access to a mac I'll give this a try. In the meantime any help on this would be very much appreciated (@mseri mentioned that he may look at it).

**Comment by LaurentMazare** [comment] 2019-01-12 22:07
I made some tweaks to get things to compile from source on macos.
This requires downloading mklml as it's not packaged with libtorch currently, e.g. by extracting these [https://github.com/intel/mkl-dnn/releases/download/v0.17.2/mklml_win_2019.0.1.20180928.zip](binaries) and copying `libmklml.dylib` and `libiomp5.dylib` to the torch lib directory (e.g. in `.opam/default/lib/libtorch/lib`.
When I get a chance I'll tweak the libtorch opam package to also include these libraries so that everything gets automated.

**Comment by LaurentMazare** [comment] 2019-01-21 13:21
As per #6 it seems that the new opam package works on macos. Please give it a try and feel free to re-open should you run into any issue or have additional feedback (I now have access to a macos box so should be able to help - although I don't have it this week).

**Closed by LaurentMazare** 2019-01-21 13:21 UTC

**Comment by nilsbecker** [comment] 2019-01-25 16:44
hmm. i tried it: i installed pytorch via anaconda and then reinstalled the current opam version of ocaml-torch. in utop i do `#require "torch.toplevel";;`. this yields:
```
Cannot load required shared library dlltorch_core_stubs.
Reason: /Users/nbecker/.opam/4.07.1+flambda/lib/stublibs/dlltorch_core_stubs.so: dlopen(/Users/nbecker/.opam/4.07.1+flambda/lib/stublibs/dlltorch_core_stubs.so, 10): Library not loaded: @rpath/libc10.dylib
  Referenced from: /Users/nbecker/.opam/4.07.1+flambda/lib/stublibs/dlltorch_core_stubs.so
  Reason: image not found.
Error: Reference to undefined global `Torch_core__Wrapper'
```
some linking problem -- what could be the cause?

**Comment by LaurentMazare** [comment] 2019-01-25 17:24
Interesting thanks for the report. Could you try building a native app to see if this works ?

Also when you launch utop, can you try setting DYLD_LIBRARY_PATH to point to the directory that contains libc10.dylib ?
(There could also be some issue caused by mixing the anaconda and opam package.)

**Comment by nilsbecker** [comment] 2019-01-28 10:38
building and running the char_rnn example works fine as well -- no env setup required for that.

**Comment by LaurentMazare** [comment] 2019-01-28 10:55
Excellent thanks, I'll tweak the readme to reflect this.

**Comment by brando90** [comment] 2021-02-12 17:16
> As per #6 it seems that the new opam package works on macos. Please give it a try and feel free to re-open should you run into any issue or have additional feedback (I now have access to a macos box so should be able to help - although I don't have it this week).

I recently tried to install `opam install torch` and I get a linker issue. What was the commands you run to install on mac os x?

My error:

```
(automl-meta-learning) brando~/ML4Coq ❯ opam install torch
[NOTE] It seems you have not updated your repositories for a while. Consider updating them with:
       opam update

The following actions will be performed:
  - install torch 0.10

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[torch.0.10] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of torch failed at "/Users/brando/.opam/opam-init/hooks/sandbox.sh build dune build -p torch -j 15".

#=== ERROR while compiling torch.0.10 =========================================#
# context     2.0.7 | macos/x86_64 | ocaml-variants.4.07.1+flambda | https://opam.ocaml.org#bcb3c300
# path        ~/.opam/4.07.1+flambda/.opam-switch/build/torch.0.10
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p torch -j 15
# exit-code   1
# env-file    ~/.opam/log/torch-46975-6d07ae.env
# output-file ~/.opam/log/torch-46975-6d07ae.out
### output ###
#   ocamlmklib src/wrapper/dlltorch_core_stubs.so,src/wrapper/libtorch_core_stubs.a (exit 2)
# (cd _build/default && /Users/brando/.opam/4.07.1+flambda/bin/ocamlmklib.opt -g -o src/wrapper/torch_core_stubs src/wrapper/torch_api.o src/wrapper/torch_stubs.o -lstdc++ -Wl,-rpath,/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/lib -L/Users/brando/anaconda3/envs/automl-meta-learning/lib/python3.8/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -Wl,-rpath[...]
# ld: file not found: @rpath/libiomp5.dylib for architecture x86_64
# clang: error: linker command failed with exit code 1 (use -v to see invocation)



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build torch 0.10
+- 
- No changes have been performed
# Run eval $(opam env) to update the current shell environment

```

I've ran the following .sh script so far:

```

opam update

#apt-get install pkg-config
brew install pkg-config

# apt-get install libffi
brew install libffi

opam install torch
```
